### ISSUE TITLE
js is not complied by default

### ISSUE THREAD

**Issue by ohadlevy** [abenari/spice-html5-rails#1]
I didnt have time  to test, but you would need to expecility add it to be added, as described at http://edgeguides.rubyonrails.org/engines.html#separate-assets-precompiling, e.g.

``` ruby
initializer "blorgh.assets.precompile" do |app|
  app.config.assets.precompile += %w(spice-html.js)
end
```

**Comment by kbrock** [comment]
Many people will probably just include this into the `application.js` file.
Think having people add the precompile themselves only if they need this is the best route.
